<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="8" hostname="ZenBook" name="com.epam.tat.calctest.testng.SumTest" tests="9" failures="1" timestamp="29 сен 2018 11:08:27 GMT" time="0.013" errors="0">
  <testcase name="sumLongTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumLongTest -->
  <testcase name="setUp" time="0.013" classname="com.epam.tat.calctest.testng.SumTest">
    <failure type="java.lang.AssertionError" message="Calculator object not created! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Calculator object not created! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.epam.tat.calctest.testng.Creation.setUp(Creation.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- setUp -->
  <testcase name="sumDoubleTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumDoubleTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumLongTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumLongTest -->
  <testcase name="sumLongTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumLongTest -->
  <testcase name="sumDoubleTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumDoubleTest -->
  <testcase name="sumLongTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumLongTest -->
  <testcase name="sumDoubleTest" time="0.000" classname="com.epam.tat.calctest.testng.SumTest">
    <skipped/>
  </testcase> <!-- sumDoubleTest -->
</testsuite> <!-- com.epam.tat.calctest.testng.SumTest -->
